const dataMemory = [
  { id: 1, icon: 'face', color: '#e2aa50', stat: '' },
  { id: 1, icon: 'face', stat: '' },
  { id: 2, icon: 'settings', stat: '' },
  { id: 2, icon: 'settings', stat: '' },
  { id: 3, icon: 'favorite', stat: '' },
  { id: 3, icon: 'favorite', stat: '' },
  { id: 4, icon: 'language', stat: '' },
  { id: 4, icon: 'language', stat: '' },
  { id: 5, icon: 'fingerprint', stat: '' },
  { id: 5, icon: 'fingerprint', stat: '' },
  { id: 6, icon: 'thumb_up', stat: '' },
  { id: 6, icon: 'thumb_up', stat: '' },
  { id: 7, icon: 'question_answer', stat: '' },
  { id: 7, icon: 'question_answer', stat: '' },
  { id: 8, icon: 'lightbulb', stat: '' },
  { id: 8, icon: 'lightbulb', stat: '' },

  { id: 9, icon: 'pets', stat: '' },
  { id: 9, icon: 'pets', stat: '' },
  { id: 10, icon: 'android', stat: '' },
  { id: 10, icon: 'android', stat: '' },
  { id: 11, icon: 'support', stat: '' },
  { id: 11, icon: 'support', stat: '' },
  { id: 12, icon: 'group_work', stat: '' },
  { id: 12, icon: 'group_work', stat: '' },
  { id: 13, icon: 'nightlight_round', stat: '' },
  { id: 13, icon: 'nightlight_round', stat: '' },
  { id: 14, icon: 'label_important', stat: '' },
  { id: 14, icon: 'label_important', stat: '' },
  { id: 15, icon: 'commute', stat: '' },
  { id: 15, icon: 'commute', stat: '' },
  { id: 16, icon: 'flight_land', stat: '' },
  { id: 16, icon: 'flight_land', stat: '' },

  { id: 17, icon: 'pregnant_woman', stat: '' },
  { id: 17, icon: 'pregnant_woman', stat: '' },
  { id: 18, icon: 'offline_pin', stat: '' },
  { id: 18, icon: 'offline_pin', stat: '' },
  { id: 19, icon: 'alarm_add', stat: '' },
  { id: 19, icon: 'alarm_add', stat: '' },
  { id: 20, icon: 'spellcheck', stat: '' },
  { id: 20, icon: 'spellcheck', stat: '' },
  { id: 21, icon: 'eject', stat: '' },
  { id: 21, icon: 'eject', stat: '' },
  { id: 22, icon: 'gif_box', stat: '' },
  { id: 22, icon: 'gif_box', stat: '' },
  { id: 23, icon: 'currency_exchange', stat: '' },
  { id: 23, icon: 'currency_exchange', stat: '' },
  { id: 24, icon: 'shopping_cart_checkout', stat: '' },
  { id: 24, icon: 'shopping_cart_checkout', stat: '' },

  { id: 25, icon: 'switch_access_shortcut_add', stat: '' },
  { id: 25, icon: 'switch_access_shortcut_add', stat: '' },
  { id: 26, icon: 'lock_reset', stat: '' },
  { id: 26, icon: 'lock_reset', stat: '' },
  { id: 27, icon: 'join_full', stat: '' },
  { id: 27, icon: 'join_full', stat: '' },
  { id: 28, icon: 'webhook', stat: '' },
  { id: 28, icon: 'webhook', stat: '' },
  { id: 29, icon: 'assured_workload', stat: '' },
  { id: 29, icon: 'assured_workload', stat: '' },
  { id: 30, icon: 'display_settings', stat: '' },
  { id: 30, icon: 'display_settings', stat: '' },
  { id: 31, icon: 'install_mobile', stat: '' },
  { id: 31, icon: 'install_mobile', stat: '' },
  { id: 32, icon: 'view_cozy', stat: '' },
  { id: 32, icon: 'view_cozy', stat: '' },
];

export default dataMemory;
